### ISSUE TITLE
how to use svg-sprites in this repo?

### ISSUE THREAD

**Issue by liamwang** [mrTimofey/webpack-starter#2]
Can you just make some pages to demonstrate how to use some features like svg-sprites of this repo?

And, thanks for your great effort on this repo. I'v learnt a lot.

**Comment by mrTimofey** [comment]
Thank you, very appreciated :)

Icons are also here, in `testable` branch. Usage is demonstrated [here](https://github.com/mrTimofey/vue-ssr-starter/blob/testable/src/app.pug#L11).

I am going to make more illustrative and community-ready examples. But right now there are too many things that can be dramatically changed after some real production experience.

You can read some info from README\`s application structure section (`assets/sprite.svg`, `assets/icons`, `build/svg-sprite`).

There is the npm command `npm run build:sprites` which will generate the `assets/sprite.svg` file with all svg files from `assets/icons` folder (it is executed with `npm run build` as well). This file is imported and inserted to the application page automatically so there are no more actions needed to use the icons.

In your templates you can just use the `icon(name="svg-icon-file-name")` component which is implicitly imported from the `components/shared/icon` file.

**Comment by liamwang** [comment]
That's greate! 
Thanks!
