### ISSUE TITLE
New route

### ISSUE THREAD

**Issue by farhad-arjmand** [mrTimofey/webpack-starter#4]
how i can add new route?

**Comment by farhad-arjmand** [comment]
how to add params iin route?

**Comment by mrTimofey** [comment]
[Here](https://github.com/mrTimofey/vue-ssr-starter/blob/testable/src/pages/examples/async-item.vue) is an example for a page component with route params bound to props. For more information you can read [appropriate README section](https://github.com/mrTimofey/vue-ssr-starter#ssr-related-component-features).

**Comment by mrTimofey** [comment]
I've detected a mistake in README, `routeParams` should be `routePath`. Sorry for thath, I've just fixed it.
