### ISSUE TITLE
how to create route for CSS and JS in assets

### ISSUE THREAD

**Issue by farhad-arjmand** [mrTimofey/webpack-starter#5]

**Comment by mrTimofey** [comment]
You don't need routes for CSS and JS files. You definitely do something wrong or I just don't understand what do you really want to achieve.

**Comment by farhad-arjmand** [comment]
i want to link css file to layout
or i want to link image to img tag , icant find correct path

**Comment by mrTimofey** [comment]
CSS is handled automatically, you don't have to do anything manually.
To link image just place it in the `assets/i` directory and require/import it anywhere you want. To import image from template directly use something like `img(src="~assets/i/image.jpg")` and Webpack will resolve it.

**Comment by farhad-arjmand** [comment]
thanks

**Comment by farhad-arjmand** [comment]
i want to link icon to meta tags , but not found
link(rel='mask-icon', href='~assets/icons/safari-pinned-tab.svg', color='#5bbad5')

or

link(rel='mask-icon', href='/assets/icons/safari-pinned-tab.svg', color='#5bbad5')


Page not found :(

**Comment by mrTimofey** [comment]
[Read this](https://vue-loader.vuejs.org/guide/asset-url.html#transform-rules)

But I advise you to learn some basic stuff before going deeper into Vue and SSR. Try to use something like [Nuxt](https://nuxtjs.org/) or [Ream](https://ream.js.org/) which are well documented and have community. My vue-ssr-starter is for those who want to make all the things from scratch and that is definitely not what you should do now IMHO.
